# result app pod
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 8081

---
# UI External Service
# service
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  selector: #should be same as the lables of redis pod
    name: result-app-pod
    app: demo-voting-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30004
