# voting app ui pod
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod #same acceoss all pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
---
# UI External Service
# service
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  selector: #should be same as the lables of redis pod
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
