# deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
# strategy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mongo
    # pod specification
    spec:
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

      # pods container
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: mongo-storage

          # taking values from configMapRef (load entire configmapref to the deployment file)
          envFrom:
            - configMapRef:
                name: mongodb-config

---
# services to expose 27017 port
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
