apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql-pv

# specs
spec:
  # declare capacity
  capacity:
    storage: 1Gi

  # Access Modes
  accessModes:
    - ReadWriteOnce

  # mount hostpath
  hostPath:
    path: "/mnt/data/mysql-pv"

  # storage class
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
