apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-pvc

spec:
  # request for storage
  resources:
    requests:
      storage: 1Gi
  # access mode
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
