apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-logs-ps

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/mysql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-logs-pvc

spec:
  accessModes:
    - ReadWriteOnce
  # resource request
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
