apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin

# global specification
spec:
  replicas: 1

  selector:
    matchLabels:
      app: phpmyadmin

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: phpmyadmin

    spec:
      containers:
        - name: phpmyadmin-container
          image: phpmyadmin/phpmyadmin
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service #(This should be the service name of dependenet)
            - name: PMA_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - port: 8080
      targetPort: 80
      # nodePort: 30123
