apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
    tier: database
spec:
  containers:
    - name: mysql-container
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpaas
