apiVersion: v1
kind: Pod
metadata:
  # podname
  name: nginx-pod
  labels: #labels are added becuase to link resources like (deployment, services) with each other
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
