apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe-pod
  labels:
    app: nginx-probe
spec:
  restartPolicy: Always
  containers:
    - name: nginx-pod
      image: nginx:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80

      # probes
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
