apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdata
  labels:
    app: netdata

spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdata
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: netdata
      labels:
        app: netdata
    spec:
      containers:
        - name: netdata-container
          image: netdata/netdata
          imagePullPolicy: Always
          ports:
            - containerPort: 19999
