apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx

# global specification
spec:
  replicas: 1

  # selector
  selector:
    matchLabels:
      app: my-nginx

  # template
  template:
    metadata:
      labels:
        app: my-nginx

    # pod specs
    spec:
      containers:
        - name: my-nginx-container
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi" #128MB
              cpu: "500m" #500 millicpu (.5 cpu or 1/2 cpu)
