apiVersion: apps/v1
kind: Deployment
metadata:
  name: iap-backend
  labels:
    app: iap-backend

# global spec
spec:
  replicas: 3

  # strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # selector
  selector:
    matchLabels:
      app: iap-backend

  # pod template
  template:
    metadata:
      labels:
        app: iap-backend

    spec:
      containers:
        - name: iap-backend-container
          image: thecuriousteam/iap-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          # resources
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          # livenessprobe
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: iap-backend-services
  labels:
    app: iap-backend-services

spec:
  selector:
    app: iap-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
