apiVersion: v1
kind: Service
metadata:
  name: iap-backend-externalname
  labels:
    app: iap-backend-externalname

spec:
  type: ExternalName

  selector:
    app: iap-backend

  ports:
    - port: 5000
      targetPort: 5000

  externalName: workwithus.cbsecosystem.org


# we need to access like this curl https://workwithus-service.default.svc.cluster.local
