apiVersion: v1
kind: Service
metadata:
  name: iap-backend-nodeport
  labels:
    app: iap-backend-nodeport
spec:
  type: NodePort
  selector:
    app: iap-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30123
